name: Publish

on:
  push:
    branches:
      - main

jobs:
  tag-pre-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.autotag.outputs.tagname }}
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      id: autotag
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy: package
        commit_message_template: "🔖 {{number}} {{message}} (by {{author}})\nSHA: {{sha}}\n."

  github-release:
    runs-on: ubuntu-latest
    needs: tag-pre-release
    if: ${{ needs.tag-pre-release.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ needs.tag-pre-release.outputs.tag }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: github-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag-pre-release.outputs.tag }}
          draft: false
          prerelease: false

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Install
        run: npm ci

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
